### ISSUE TITLE
consistent crashes on Android12

### ISSUE THREAD

**Issue by kainbanford** [Orna-tools/ornaassistant#16]
I'm super grateful for the continued development of this app.

However, it no longer seems to function on Android 12 devices (previous version worked on all my old devices, including an Android 9 and 10 device) 

It just doesn't "do" anything, I can load it up and browse through screens and things like "enable accessibility features" seem to take me to the right place, but it doesn't count dungeons, it doesn't auto-assess and I don't know what else it's supposed to do (those were the only features available to me as a non-burrito kingdom)

Occasionally my phone will tell me "ornaassistant is crashing frequently" -- I generated an android "bug report" but it's 31mb in size -- if you message me an email address to share it to, I'll be happy to share that privately.
![Screenshot_20240202-121734_One UI Home](https://github.com/Orna-tools/ornaassistant/assets/8973888/77b627d1-2ca3-479c-bb09-47a2ecdcdd8f)

**Comment by Lloir** [comment]
I need to add Android 12/13 compatibility

**Comment by Lloir** [comment]
fixed

**Comment by kainbanford** [comment]
confirming that https://github.com/Orna-tools/ornaassistant/releases/tag/1.1.20 works great on my android12 phone!
